// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkZV_gfV9KGhdR7DTW_LRbxoWTb0e9eKg',
    appId: '1:410073535328:android:eb2a09e55d1d14e5098405',
    messagingSenderId: '410073535328',
    projectId: 'my-restaurant-34711',
    storageBucket: 'my-restaurant-34711.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFTHKuyUTcDaZ5sBXWjvXVZR3z0fYR9fA',
    appId: '1:410073535328:ios:8c83a7e41b6736f7098405',
    messagingSenderId: '410073535328',
    projectId: 'my-restaurant-34711',
    storageBucket: 'my-restaurant-34711.firebasestorage.app',
    iosBundleId: 'com.example.restaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_28gNcDQBs1MShupNRrtb88ivANLpFbg',
    appId: '1:410073535328:web:4a6d893dfab127b1098405',
    messagingSenderId: '410073535328',
    projectId: 'my-restaurant-34711',
    authDomain: 'my-restaurant-34711.firebaseapp.com',
    storageBucket: 'my-restaurant-34711.firebasestorage.app',
    measurementId: 'G-8VCV4LVW8H',
  );
}
